replicaCount: 5
image:
  repository: walkerkyle/nlw.service.passin
  pullPolicy: Always
  tag: 660b08b
  port: 3333
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
autoscaling:
  enabled: true
  minReplicas: 5
  maxReplicas: 8
  targetMemoryUtilizationPercentage: 75
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
startupProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 40
  failureThreshold: 5
  periodSeconds: 10
livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 60
  failureThreshold: 5
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 60
  failureThreshold: 5
  periodSeconds: 10
